_target_: adjoint_samplers.components.matcher.AdjointVPMatcher

grad_state_cost:
  _target_: adjoint_samplers.components.state_cost.ZeroGradStateCost

buffer:
  _target_: adjoint_samplers.components.buffer.BatchBuffer
  buffer_size: ${adjoint_matcher.buffer_size}
