# @package _global_
defaults:
- override /hydra/launcher: submitit_slurm

scratch_dir: /scratch/aburger/as

# hydra:
#   run:
#     dir: ./results/local/${now:%Y.%m.%d}/${now:%H%M%S}
#   sweep:
#     dir: ./results/${now:%Y.%m.%d}/${now:%H%M%S}
#     subdir: ${hydra.job.num}
#   launcher:
#     max_num_timeout: 100000
#     timeout_min: 4319
#     gpus_per_node: 1
#     tasks_per_node: ${hydra.launcher.gpus_per_node}
#     cpus_per_task: 10
#     nodes: 1
#     constraint: volta16gb
#     mem_per_gpu: 30gb
